### PR TITLE
[fdbshow] fix fdbshow, show arp commands

### PR DESCRIPTION
**Pull request by dmytroxshevchuk**
Fix issue:
https://github.com/Azure/sonic-buildimage/issues/5927

### CODE REVIEW

**Review by prsunny — APPROVED** [review]
@jleveque , can you review and take a look at the issue reported?

**Comment by jleveque** [comment]
@qiluo-msft to comment, as the issue appears to be due to swsssdk change.

**Review by bingwang-ms — APPROVED** [review]

**Comment by dmytroxshevchuk** [comment]
@qiluo-msft, please take a look to this PR

**Comment by prsunny** [comment]
@qiluo, this is blocking some tests. Merging for now.

**Comment by qiluo-msft** [comment]
Sorry for late. I don't quite understand why this fix works, could you explain?

**Comment by bingwang-ms** [comment]
I spent some time in investigating this issue, and believe this fix will address the issue correctly.
The root cause for this issue is we use  ```SonicV2Connector``` from ```swsscommon.swsscommon``` in ```fdbshow``` master branch. The ```keys``` method is implemented in C++ and wrapped into a python interface.
```
def keys(self, *args, **kwargs):
        return _swsscommon.SonicV2Connector_keys(self, *args, **kwargs)

```
Therefore, a exception will be raised if we pass an unicode to the interface.
```
TypeError("in method 'SonicV2Connector_keys', argument 3 of type 'char const *'",)
```
So, a conversion to str will address the issue.

**Pull request merged**
