### PR TITLE
[port_util] Fix issue: port_util.get_vlan_interface_oid_map should not raise exception when DB has not RIF data

### PR DESCRIPTION
**Pull request by Junchao-Mellanox**
**Why I did this?**

port_util.get_vlan_interface_oid_map would raise exception when there is no RIF configured, and it would causes snmpagent not work. This PR is to fix it.

```
#012Traceback (most recent call last):
#012File "/usr/local/lib/python3.7/dist-packages/ax_interface/mib.py", line 37, in start
#012    self.reinit_data()#012  File "/usr/local/lib/python3.7/dist-packages/sonic_ax_impl/mibs/ietf/rfc1213.py", line 233, in reinit_data
#012    self.vlan_oid_name_map = Namespace.get_sync_d_from_all_namespace(mibs.init_sync_d_vlan_tables, self.db_conn)
#012  File "/usr/local/lib/python3.7/dist-packages/sonic_ax_impl/mibs/__init__.py", line 651, in get_sync_d_from_all_namespace
#012    ns_tuple = per_namespace_func(db_conn)
#012  File "/usr/local/lib/python3.7/dist-packages/sonic_ax_impl/mibs/__init__.py", line 341, in init_sync_d_vlan_tables
#012    vlan_name_map = port_util.get_vlan_interface_oid_map(db_conn)
#012  File "/usr/local/lib/python3.7/dist-packages/swsssdk/port_util.py", line 167, in get_vlan_interface_oid_map
#012    rif_name_map = db.get_all('COUNTERS_DB', 'COUNTERS_RIF_NAME_MAP', blocking=True)
#012  File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1751, in get_all
#012    return dict(super(SonicV2Connector, self).get_all(db_name, _hash, blocking))
#012  File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1708, in get_all
#012    return _swsscommon.SonicV2Connector_Native_get_all(self, db_name, _hash, blocking)
#012RuntimeError: Key '{COUNTERS_RIF_NAME_MAP}' unavailable in database '{COUNTERS_DB}'
```

**How I did this:**
check redis key exists first before calling get_all.

### CODE REVIEW

**Review by keboliu — APPROVED** [review]

**Review by keboliu — APPROVED** [review]

**Review by liat-grozovik — DISMISSED** [review]

**Comment by liat-grozovik** [comment]
@qiluo-msft could you please help to signoff?

**Comment by Junchao-Mellanox** [comment]
Hi @qiluo-msft , could you please review and sign-off?

**Comment by dprital** [comment]
Hi @qiluo-msft  - Can you please direct this PR to the relevant maintainer ?

**Comment by liat-grozovik** [comment]
@qiluo-msft due to limited permission please add a label of bug as well as requested for 202111

**Comment by qiluo-msft** [comment]
> def get_vlan_interface_oid_map(db):

you can add a new parameter `blocking` with default value `True`.

Change the internal blocking accordingly. No need to check `exists`.

The benefit is to keep old behavior, and allow client code to change behavior case by case.

---
Refers to: src/swsssdk/port_util.py:162 in 9beb381. [](commit_id = 9beb381db7c2910b407252287bd2820f4f4b5e47, deletion_comment = False)

**Comment by Junchao-Mellanox** [comment]
> > def get_vlan_interface_oid_map(db):
> 
> you can add a new parameter `blocking` with default value `True`.
> 
> Change the internal blocking accordingly. No need to check `exists`.
> 
> The benefit is to keep old behavior, and allow client code to change behavior case by case.
> 
> Refers to: src/swsssdk/port_util.py:162 in [9beb381](https://github.com/Azure/sonic-py-swsssdk/commit/9beb381db7c2910b407252287bd2820f4f4b5e47). [](commit_id = [9beb381](https://github.com/Azure/sonic-py-swsssdk/commit/9beb381db7c2910b407252287bd2820f4f4b5e47), deletion_comment = False)

Hi @qiluo-msft , I would like to confirm your comment here:

1. add a parameter to get_vlan_interface_oid_map
```python
def get_vlan_interface_oid_map(db, blocking=True):
    ...
```
2. and change snmpagent code to call it like:
```
get_vlan_interface_oid_map(db, blocking=False)
```

Correct?

**Comment by SuvarnaMeenakshi** [comment]
> > > def get_vlan_interface_oid_map(db):
> > 
> > 
> > you can add a new parameter `blocking` with default value `True`.
> > Change the internal blocking accordingly. No need to check `exists`.
> > The benefit is to keep old behavior, and allow client code to change behavior case by case.
> > Refers to: src/swsssdk/port_util.py:162 in [9beb381](https://github.com/Azure/sonic-py-swsssdk/commit/9beb381db7c2910b407252287bd2820f4f4b5e47). [](commit_id = [9beb381](https://github.com/Azure/sonic-py-swsssdk/commit/9beb381db7c2910b407252287bd2820f4f4b5e47), deletion_comment = False)
> 
> Hi @qiluo-msft , I would like to confirm your comment here:
> 
> 1. add a parameter to get_vlan_interface_oid_map
> 
> ```python
> def get_vlan_interface_oid_map(db, blocking=True):
>     ...
> ```
> 
> 2. and change snmpagent code to call it like:
> 
> ```
> get_vlan_interface_oid_map(db, blocking=False)
> ```
> 
> Correct?

```
--- a/src/swsssdk/port_util.py
+++ b/src/swsssdk/port_util.py
@@ -164,13 +164,13 @@ def get_rif_port_map(db):
 
     return rif_port_oid_map
 
-def get_vlan_interface_oid_map(db):
+def get_vlan_interface_oid_map(db, blocking=True):
     """
         Get Vlan Interface names and sai oids
     """
     db.connect('COUNTERS_DB')
-    rif_name_map = db.get_all('COUNTERS_DB', 'COUNTERS_RIF_NAME_MAP', blocking=True)
-    rif_type_name_map = db.get_all('COUNTERS_DB', 'COUNTERS_RIF_TYPE_MAP', blocking=True)
+    rif_name_map = db.get_all('COUNTERS_DB', 'COUNTERS_RIF_NAME_MAP', blocking=blocking)
+    rif_type_name_map = db.get_all('COUNTERS_DB', 'COUNTERS_RIF_TYPE_MAP', blocking=blocking)
```

**Comment by SuvarnaMeenakshi** [comment]
@mlok-nokia - fyi

**Comment by SuvarnaMeenakshi** [comment]
@Junchao-Mellanox created snmp PR https://github.com/Azure/sonic-snmpagent/pull/246, depends on this PR.

**Comment by qiluo-msft** [comment]
Yes.

---
In reply to: [1068646058](https://github.com/Azure/sonic-py-swsssdk/pull/117#issuecomment-1068646058) [](http://example.com/codeflow?ancestors=1068646058,1068646058)

**Comment by Junchao-Mellanox** [comment]
I removed previous added unit test case as this change is hard  to be covered by unit test.

**Comment by Junchao-Mellanox** [comment]
@qiluo-msft could you please review and sign off?

**Review by qiluo-msft — APPROVED** [review]

**Comment by Junchao-Mellanox** [comment]
Hi @qiluo-msft , I run the build locally and cannot reproduce the build failure. Could you please help take a look?

**Comment by qiluo-msft** [comment]
@Junchao-Mellanox We recently add coverage >= 50% enforcement to most of the repos. Could you add a unit test to coverage the missing lines? https://dev.azure.com/mssonic/build/_build/results?buildId=82325&view=codecoverage-tab

**Comment by Junchao-Mellanox** [comment]
Hi @qiluo-msft , could you please review and sign off?

**Review by qiluo-msft — APPROVED** [review]

**Comment by dprital** [comment]
@qiluo-msft - There is no 202111 branch for this repository. Is there a plan to open one ?

**Comment by SuvarnaMeenakshi** [comment]
@vperumal @anamehra @VenkatCisco fyi

**Pull request merged**
